---
- name: Discover default VPC when not provided
  amazon.aws.ec2_vpc_net_info:
    region: "{{ provision_ec2_aws_region }}"
    filters:
      isDefault: true
  register: provision_ec2_default_vpc
  when: (provision_ec2_aws_vpc_id | default('', true) | string | trim | length) == 0
  delegate_to: "{{ provision_control_host }}"
  run_once: true

- name: Use discovered VPC ID
  ansible.builtin.set_fact:
    provision_ec2_aws_vpc_id: "{{ provision_ec2_default_vpc.vpcs[0].vpc_id }}"
  when:
    - (provision_ec2_aws_vpc_id | default('', true) | string | trim | length) == 0
    - provision_ec2_default_vpc.vpcs | default([]) | length > 0

- name: Discover default subnet when not provided
  amazon.aws.ec2_vpc_subnet_info:
    region: "{{ provision_ec2_aws_region }}"
    filters:
      vpc-id: "{{ provision_ec2_aws_vpc_id }}"
      default-for-az: true
  register: provision_ec2_default_subnets
  when: (provision_ec2_aws_subnet_id | default('', true) | string | trim | length) == 0
  delegate_to: "{{ provision_control_host }}"
  run_once: true

- name: Use discovered subnet ID
  ansible.builtin.set_fact:
    provision_ec2_aws_subnet_id: "{{ provision_ec2_default_subnets.subnets[0].subnet_id }}"
  when:
    - (provision_ec2_aws_subnet_id | default('', true) | string | trim | length) == 0
    - provision_ec2_default_subnets.subnets | default([]) | length > 0

- name: Ensure network identifiers are available
  ansible.builtin.assert:
    that:
      - provision_ec2_aws_vpc_id is defined and (provision_ec2_aws_vpc_id | string | trim) | length > 0
      - provision_ec2_aws_subnet_id is defined and (provision_ec2_aws_subnet_id | string | trim) | length > 0
    fail_msg: "Unable to resolve provision_ec2_aws_vpc_id/provision_ec2_aws_subnet_id. Provide values explicitly or ensure defaults exist in the region."

- name: Synchronize legacy network facts
  ansible.builtin.set_fact:
    provision_ec2_vpc_id: "{{ provision_ec2_aws_vpc_id }}"
    provision_ec2_subnet_id: "{{ provision_ec2_aws_subnet_id }}"
