---
- name: Ensure security group for instance exists
  amazon.aws.ec2_security_group:
    name: "{{ provision_ec2_security_group_name }}"
    description: "Security group for {{ provision_ec2_effective_name }}"
    vpc_id: "{{ provision_ec2_aws_vpc_id }}"
    region: "{{ provision_ec2_aws_region }}"
    rules: "{{ provision_ec2_security_group_rules }}"
    tags:
      Name: "{{ provision_ec2_security_group_name }}"
      Environment: "{{ provision_ec2_environment }}"
      Project: "{{ provision_ec2_project }}"
      ManagedBy: ansible
      CreatedAt: "{{ ansible_date_time.iso8601 }}"
  register: provision_ec2_security_group_result

  run_once: true
  tags: ['provision', 'security_group']

- name: Share security group details
  ansible.builtin.set_fact:
    provision_ec2_security_group_id: >
      "{{ provision_ec2_security_group_result.group_id | default(provision_ec2_security_group_result.security_group_id | default(omit)) }}"

  run_once: true
  tags: ['provision', 'security_group']
