---
collections:
  - name: community.hashi_vault
    version: ">=4.0.0"
  - name: ansible.windows
    version: ">=1.14.0"
  - name: amazon.aws
    version: ">=10.1.1"
  - name: community.windows
    version: ">=2.2.0"
  - name: community.crypto
    version: ">=2.17.0"
  - name: trippsc2.mssql
