argument_specs:
  main:
    short_description: Provision a Windows EC2 instance with SSH/Vault integration
    options:
      provision_ec2_aws_region:
        type: str
        required: false
        description: AWS region used for all AWS API calls.
      provision_ec2_aws_vpc_id:
        type: str
        required: false
        description: Existing VPC ID. Discovered automatically when omitted.
      provision_ec2_aws_subnet_id:
        type: str
        required: false
        description: Existing subnet ID. Discovered automatically when omitted.
      provision_ec2_name_tag:
        type: str
        required: true
        description: Name tag assigned to the EC2 instance and derived resources.
      provision_ec2_instance_type:
        type: str
        required: false
        description: EC2 instance type to launch.
      provision_ec2_image_id:
        type: str
        required: false
        description: AMI ID for the Windows image.
      provision_ec2_root_volume_size:
        type: int
        required: false
        description: Size in GiB of the root volume.
      provision_ec2_assign_public_ip:
        type: bool
        required: false
        description: Whether to assign a public IPv4 address.
      provision_ec2_security_group_name:
        type: str
        required: false
        description: Name for the security group that allows SSH/RDP/SQL access.
      provision_ec2_keypair_name:
        type: str
        required: false
        description: Reuse an existing AWS key pair instead of generating one.
      provision_ec2_configure_route53:
        type: bool
        required: false
        description: When true, create/update a Route53 record for the instance.
      provision_ec2_route53_zone:
        type: str
        required: false
        description: Hosted zone ID used for Route53 record creation.
      provision_ec2_route53_record_name:
        type: str
        required: false
        description: Fully-qualified DNS name for the Route53 record. Defaults to the instance name when omitted.

      vault_addr:
        type: str
        required: false
        description: Base URL for the Vault cluster when not using vault_url.
      vault_url:
        type: str
        required: false
        description: Alias option for Vault server address; takes precedence over vault_addr.
      vault_role_id:
        type: str
        required: false
        description: Vault AppRole role_id for authentication.
      vault_secret_id:
        type: str
        required: false
        description: Vault AppRole secret_id for authentication.
      vault_kv_mount:
        type: str
        required: false
        description: KV v2 mount point where SSH secrets are stored.
      vault_ssh_path:
        type: str
        required: false
        description: Path (relative to the KV mount) for the SSH secret. Defaults to windows/ssh/<instance-name>.
      vault_verify:
        type: bool
        required: false
        description: Whether to validate Vault TLS certificates.
      vault_auth_mount_point:
        type: str
        required: false
        description: Mount point for the AppRole auth method (defaults to approle).
